src/Mushkin/VitformsBundle/Form/Type/SkillType.php
<?php
namespace Mushkin\VitformsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SkillType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('number', null, array(
                'label' => 'Название нового умения: ',
                'attr' =>array(
                    'class'=>'form-control col-sm-4'
                ),
            ))
            ->add('description', null, array(
                'label' => 'Описание нового умения: ',
                'attr' =>array(
                    'class'=>'form-control col-sm-4'
                ),
            ))
        ;
    }

        public function getName()
    {
        return 'skill';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mushkin\VitformsBundle\Entity\Skill',
            'csrf_protection' => false,
        ));
    }
}

src/Mushkin/VitformsBundle/Controller/DefaultController.php
<?php

namespace Mushkin\VitformsBundle\Controller;

use Mushkin\VitformsBundle\Entity\User;
use Mushkin\VitformsBundle\Form\Type\SkillType;
use Mushkin\VitformsBundle\Form\Type\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Mushkin\VitformsBundle\Entity\Skill;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction()
    {

        return $this->render('MushkinVitformsBundle:Default:index.html.twig',
            ['Users' => $this->getAllUsers(),'Skills' => $this->getAllSkills()]);
    }

    public function AddUserAction(Request $request)
    {
        $user = new user();
//        $skill = $this->getDoctrine()->getManager()->getRepository('MushkinVitformsBundle:Skill')->find('1');
//        $user->addSkill($skill);
        $form = $this->createForm(new UserType(), $user);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->persist($user);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirect($this->generateUrl('mushkin_vitforms_homepage'));
        }

        return $this->render('MushkinVitformsBundle:Default:AddUser.html.twig',
            [
                'Users' => $this->getAllUsers(),
                'Skills' => $this->getAllSkills(),
                'form' => $form->createView(),
            ]);
    }

    public function AddSkillAction(Request $request)
    {
        $skill = new Skill();
        $user = $this->getDoctrine()->getManager()
            ->getRepository('MushkinVitformsBundle:User')->findOneById('1');
        $skill->addSkillUser($user);

        $form = $this->createForm(new SkillType(), $skill);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->persist($skill);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirect($this->generateUrl('mushkin_vitforms_homepage'));
    }

        return $this->render('MushkinVitformsBundle:Default:AddSkill.html.twig',
            [
                'Users' => $this->getAllUsers(),
                'Skills' => $this->getAllSkills(),
                'form' => $form->createView(),
            ]);
    }

    public function getAllUsers()
    {
        $Users = $this->getDoctrine()->getManager()
            ->getRepository('MushkinVitformsBundle:User')->findAll();

        return $Users;
    }

    public function getAllSkills()
    {
        $Skills = $this->getDoctrine()->getManager()
            ->getRepository('MushkinVitformsBundle:Skill')->findAll();

        return $Skills;
    }
}

src/Mushkin/VitformsBundle/Resources/views/Default/AddUser.html.twig
{% extends "MushkinVitformsBundle:Default:index.html.twig" %}

{% block forms %}
    <h3>Добавление нового работника:</h3><br>
    <div class="col-md-12">
        <div class="form-horizontal">
            <form role="form" method="post">
          {{ form_errors(form) }}

            <div class="form-group">
                <div class="col-sm-2 control-label">
                    {{ form_label(form.name, 'Имя работника:') }}
                </div>
                <div class="col-sm-4">
                    {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-2 control-label">
                    {{ form_label(form.secondName, 'Фамилия работника:') }}
                </div>
                <div class="col-sm-4">
                    {{ form_widget(form.secondName, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-2 control-label">
                    {{ form_label(form.age, 'Возвраст работника:') }}
                </div>
                <div class="col-sm-4">
                    {{ form_widget(form.age, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>

        <h4>Умения:</h4>
        <ul class="skills" data-prototype="{{ form_widget(form.skills.vars.prototype)|e }}" >
            {% for skillfield in form.skills %}
                <li>
                    {{ form_errors(skillfield) }}
                    <div class="form-group">
                        <div class="col-sm-2 control-label">
                            {{ form_label(skillfield.number) }}
                        </div>
                        <div class="col-sm-4">
                            {{ form_widget(skillfield.number, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2 control-label">
                            {{ form_label(skillfield.description) }}
                        </div>
                        <div class="col-sm-4">
                            {{ form_widget(skillfield.description, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>

                </li>
            {% endfor %}
        </ul>
            <div class="col-sm-12">
                <button type="submit" class="btn btn-lg btn-primary">Создать</button>
            </div>
                </form>
        </div>
        <div class="col-sm-12">
            <br>
            <a href="{{ path('mushkin_vitforms_homepage') }}">назад</a>
            <br><br>
        </div>
    </div>
    <br><br>
{% endblock %}

src/Mushkin/VitformsBundle/Resources/views/Default/layout.html.twig
{% extends "::base.html.twig" %}

{% block title %}Welcome!{% endblock %}
{% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
{% endblock %}

{% block body %}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
{% endblock %}